### PR TITLE
slash command

### PR DESCRIPTION
**Pull request by Okhoshi**
Create a "slash-command" endpoint for Slack/Mattermost Integration:

* Allows the users to manage the RSS feeds directly from Mattermost without to restart the bot
* Persist the channels added or removed when used in Docker through the `feeds.env` file

Enable the skip of initial post of articles when the bot is booting.

(And I've tested carefully this time :) )

### CODE REVIEW

**Comment by elpatron68** [comment]
Hi @Okhoshi,

thanks again for your contributions! I had this great enhancement in mind for a while but never implemented it because of laziness.

Altough, I think we should reflcet this and the docker thing in README.md before merging.

**Comment by elpatron68** [comment]
Thanks again, @Okhoshi, let´s wait for @dbanck ´s review, he will approve then.

**Comment by dbanck** [comment]
Code looks good to me, but I can't give it a try because I'm not using Mattermost.

**Comment by Okhoshi** [comment]
I've tested it quite intensively while developing the command but I don't know if someone else want to try it before the merge ( @elpatron68 ?).

@dbanck It should also work with Slack if I understood well the documentation of Mattermost.

**Comment by elpatron68** [comment]
Hi @Okhoshi,

First of all, the feedfetcher was easy to setup using `docker-compose` - no problems at all.

Then I tried to set up the slash command thing and had some problems:

My setup:
[Is this the way it was meant to be?](https://imgur.com/gallery/N9OV7)
Where should the slash command token be entered?
If I call the command (e.g. `rss-bot list`), I get `Command with a trigger of 'rss-bot' failed`. Any ideas what went wrong?

**Comment by Okhoshi** [comment]
@elpatron68 About the setup, it seems right but I can't be sure about the address as I don't your hosts setup.

The slash command token should be placed in the compose file, instead of `<your-slash-command-token>`.
To get an insight of what got wrong, you can look at the log of the docker container (`docker-compose logs`) with the `not_silent` settings to true.

**Pull request merged**
