### PR TITLE
Fix boolean conversion

### PR DESCRIPTION
**Pull request by Okhoshi**
When coming from Environment variables, booleans are not interpreted correctly

### CODE REVIEW

**Comment by dbanck** [comment]
What do you think of using https://pypi.python.org/pypi/environs ? This would make the config much more readable.

**Comment by elpatron68** [comment]
As I see it, the project is broken at the state we have now, is that right? Perhaps we should merge this PR to get it up and running again soon? @Okhoshi @dbanck ?

**Comment by Okhoshi** [comment]
The project is not exactly broken at this time, the fact is one cannot provide Boolean and Int parameters if using the Docker setup (as it goes through environmental variables).

@dbanck: I will check your proposal asap, it might be a better solution indeed. Thanks!

_____________________________

**Comment by elpatron68** [comment]
Thanks again @Okhoshi

**Pull request merged**
